---
title: "Curriculum Vitae"
author: "Albert Vill"
date: ""
output: html_document
---

Last updated 12 May 2022  
[**PDF version here**](/AVill_CV_12May2022.pdf)

<details>
  <summary>Education</summary>

<h4>Doctor of Philosophy — Cornell University, 2022</h4>
Department of Molecular Biology and Genetics  
Field of Genetics, Genomics & Development

<h4>Bachelor of Science — Gettysburg College, 2016</h4>
Biochemistry and Molecular Biology major, *magna cum laude*  
Lincoln Scholar – highest merit-based scholarship awarded

</details>

<details>
  <summary>Research Experience</summary>

<h4>PhD Candidate — Lab of Dr. Ilana Brito, Cornell University</h4>
Designing and implementing methods to quantify changes in the composition and function of the human gut microbiome during perturbation and disease — **May 2017 – May 2022**  

<h4>HHMI Summer Research Fellow — Gettysburg College</h4>
Characterizing soil bacteriophages by host range screens and comparative genomics — **Summers 2014 & 2015**

</details>

<details>
  <summary>Publications</summary>

**Vill AC**, Rice EJ, De Vlaminck I, Danko CG, Brito IL. [Run-on sequencing
reveals transcriptional dynamics within the human microbiome](https://www.biorxiv.org/content/10.1101/2022.04.22.489220v1). **Out for Review**

Kent AG, **Vill AC** <span style="color:red">†</span>, Shi Q, Satlin MJ, Brito IL. [Widespread transfer of mobile antibiotic resistance genes within individual gut microbiomes revealed through bacterial Hi-C.](https://doi.org/10.1038/s41467-020-18164-7) *Nature Communications*. **2020** Sep 1;11(1):4379.

Delesalle VA, **Vill AC**, Tomko BE, Boas K, Burton EA, Guffey AA, Loney R, Simões MS, Tanke NT, Krukonis GP. Comparative genomics of fourteen novel Siphoviridae phages of Bacillus subtilis, including three phages closely related to SPP1. **In Preparation**

Delesalle VA, Tanke NT, **Vill AC**, Krukonis GP. [Testing hypotheses for the presence of tRNA genes in mycobacteriophage genomes.](https://doi.org/10.1080/21597081.2016.1219441) *Bacteriophage*. **2016** Aug 5;6(3):e1219441.

Pope WH, Bowman CA, Russell DA, Jacobs-Sera D, Asai DJ, Cresawn SG, Jacobs WR, Hendrix RW, Lawrence JG, Hatfull GF; **Science Education Alliance Phage Hunters Advancing Genomics and Evolutionary Science** <span style="color:red">‡</span>; Phage Hunters Integrating Research and Education; Mycobacterial Genetics Course. [Whole genome comparison of a large collection of mycobacteriophages reveals a continuum of phage genetic diversity.](https://doi.org/10.7554/elife.06416) *eLife*. **2015** Apr 28;4:e06416.

<span style="color:red">†</span> co-first author  
<span style="color:red">‡</span> consortium member, data contributor

</details>

<details>
  <summary>Presentations</summary>

**Poster** — The Human Microbiome: Ecology and Evolution Symposium  
*Run-on sequencing enables nascent metatranscriptomics of the human microbiome*. **2022** (<span style="color:red">canceled</span>) 

**Poster** — Lake Arrowhead Microbial Genomics Meeting  
*Bacterial nascent transcriptomics with precision run-on sequencing*. **2021** (<span style="color:red">canceled</span>)  

**Poster** — Biomedical Engineering Society Annual Meeting  
*Monitoring the Transfer of Antibiotic Resistance Genes in Patients with Neutropenia using Bacterial Hi-C*. **2019**

</details>

<details>
  <summary>Honors and Awards</summary>

Travel Award Recipient, [Cornell Center for Vertebrate Genomics](https://cvg.cornell.edu/scholars-past.php) — **2022**  

Seed Grant Recipient, [Genomics Innovation Hub](https://www.biotech.cornell.edu/core-facilities-brc/facilities/genomics-innovation-hub) — **2020**  

Distinguished Scholar, [Cornell Center for Vertebrate Genomics](https://cvg.cornell.edu/scholars-past.php) — **2019**  

Honorable Mention, NSF Graduate Research Fellowship — **2018**  

Herzog Teaching Fellow, Gettysburg College — **2015**  

HHMI Summer Research Fellow, Gettysburg College — **2014 & 2015**

</details>

<details>
  <summary>Service and Outreach</summary>
  
Coordinator, [Cornell Center for Vertebrate Genomics Journal Club](https://cvg.cornell.edu/journal-club.php) — **Fall 2021 - Spring 2022**  

Graduate Mentor, [Microbial Friends & Foes Research Experience for non-Cornell Undergraduates](https://cihmid.cornell.edu/academics-programs/undergraduate-programs/mff-reu-microbial-friends-foes-research-experience-for-undergraduates-non-cu-students/) — **Summer 2019**
  
Workshop Facilitator, [4-H Career Explorations](https://nys4-h.org/career-explorations) “Engineering the Microbiome” Focus Program — **June 26-28, 2018**

Graduate Fellow, [Cornell Graduate Student School Outreach Program](https://sites.google.com/view/grasshopratcornell/home) — **Spring 2018**
  
</details>

<style>
details > summary {
  font-size: 1.5em;
  padding: 10px;
  background-color: #21436e;
  border: none;
  box-shadow: 0px 0px 0px #bbbbbb;
  cursor: pointer;
  margin-left: 0%;
  margin-right: 10%;
  margin-top: 0%;
  margin-bottom: 1%;
  color: #FFFFFF;
  border-radius: 5px;
}
</style>
